#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_vlan
version_added: "0.0.1"
short_description: Create or Delete VLANs through Aruba Fabric Composer.
description: >
    This Ansible module facilitates the creation or deletion of VLANs in a fabric managed by
    the Aruba Fabric Composer. It creates VLANs based on specified names and IDs
    and updates their configuration within the fabric.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    operation:
        description: >
            Operation to be performed with the VLAN, create or delete
        type: str
        required: true
    fabric_name:
        description: >
            Name of the Fabric on which VLAN to be created or deleted from
        type: str
        required: true
    vrf_name:
        description: >
            Name of the VRF to which VLAN belongs
        type: str
        required: true
    vlan_id:
        description: >
            ID of the VLAN to be created or deleted.
        type: int
        required: true
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Create VLAN in Aruba Fabric Composer
    arubanetworks.afc.afc_vlan:
        afc_ip: "10.10.10.10"
        afc_username: "admin"
        afc_password: "password"
        operation: "create"
        fabric_name: "Aruba-Fabric"
        vrf_name: "Test-VRF"
        vlan_id: 1008

-   name: Delete VLAN in Aruba Fabric Composer
    arubanetworks.afc.afc_vlan:
        afc_ip: "10.10.10.10"
        afc_username: "admin"
        afc_password: "password"
        operation: "delete"
        fabric_name: "Aruba-Fabric"
        vrf_name: "Test-VRF"
        vlan_id: 1008
'''

RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

from pyafc.fabric import fabric
from pyafc.vrf import vrf
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import instantiate_afc_object


def main():
    module_args = dict(
        afc_ip=dict(type="str", required=True),
        afc_username=dict(type="str", required=False),
        afc_password=dict(type="str", required=False),
        auth_token=dict(type="str", required=False),
        fabric_name=dict(type="str", required=True),
        operation=dict(type="str", required=True),
        vrf_name=dict(type="str", required=True),
        vlan_id=dict(type="int", required=True)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    token = None
    ip = ansible_module.params["afc_ip"]
    if 'afc_username' in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if 'afc_password' in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if 'auth_token' in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    fabric_name = ansible_module.params["fabric_name"]
    vrf_name = ansible_module.params["vrf_name"]
    operation = ansible_module.params["operation"]
    vlan_id = ansible_module.params["vlan_id"]
    vlan_name = f"VLAN{vlan_id}"

    if token is not None:
        data = {
            "ip": ip,
            "auth_token": token
        }
    else:
        data = {
            "ip": ip,
            "username": username,
            "password": password
        }

    afc_instance = instantiate_afc_object(data=data)

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    fabric_instance = fabric.Fabric(afc_instance.client, name=fabric_name)

    vrf_instance = vrf.Vrf(afc_instance.client, name=vrf_name, fabric_uuid=fabric_instance.uuid)

    if operation == 'create':
        message, status, changed = vrf_instance.create_network(name=vlan_name, vlan_id=vlan_id)
    elif operation == 'delete':
        message, status, changed = vrf_instance.delete_network(name=vlan_name, vlan_id=vlan_id)

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
