#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_snmp
version_added: "0.0.1"
short_description: Create or delete an SNMP configuration in the specified fabric.
description: >
    This module creates or deletes an SNMP configuration in the specified fabric.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    operation:
        description: >
            Operation to be performed on an SNMP configuration, create or delete.
        type: str
        required: true
    snmp_name:
        description: >
            Name of the SNMP Configuration to be created or deleted.
        type: str
        required: true
    snmp_data:
        description: >
            SNMP configuration in dictionary format as depicted in the example. Required for create and not required for delete.
        type: dict
        required: false
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Create an SNMP configuration
    arubanetworks.afc.afc_snmp:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        snmp_name: "Test-SNMP"
        operation: "create"
        snmp_data:
            fabrics: "Test-Fabric"
            enable: true
            location: "eee"
            contact: "eee"
            community: "eee"
            agent_port: 161
            trap_port: 23
            users:
                -   level: "auth"
                    name: "eee"
                    auth_type: "SHA"
                    auth_pass: "eeeeeeeeee"
            servers:
                -   address: "1.2.3.4"
                    community: "eeeee"

-   name: Delete an SNMP configuration
    arubanetworks.afc.afc_snmp:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        snmp_name: "Test-SNMP"
        operation: "delete"
'''


RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

from pyafc.services import snmp
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import instantiate_afc_object


def main():
    module_args = dict(
        afc_ip=dict(type="str", required=True),
        afc_username=dict(type="str", required=False),
        afc_password=dict(type="str", required=False),
        auth_token=dict(type="str", required=False),
        operation=dict(type="str", required=True),
        snmp_name=dict(type="str", required=True),
        snmp_data=dict(type="dict", required=False)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    token = None
    ip = ansible_module.params["afc_ip"]
    if 'afc_username' in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if 'afc_password' in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if 'auth_token' in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    snmp_name = ansible_module.params["snmp_name"]
    operation = ansible_module.params["operation"]
    if 'snmp_data' in list(ansible_module.params.keys()):
        snmp_data = ansible_module.params["snmp_data"]

    if token is not None:
        data = {
            "ip": ip,
            "auth_token": token
        }
    else:
        data = {
            "ip": ip,
            "username": username,
            "password": password
        }

    afc_instance = instantiate_afc_object(data=data)

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    status = False
    changed = False
    message = ""

    if operation == 'create':
        snmp_instance = snmp.Snmp(afc_instance.client, name=snmp_name, **snmp_data)
        message, status, changed = snmp_instance.create_snmp(**snmp_data)
    elif operation == 'delete':
        snmp_instance = snmp.Snmp(afc_instance.client, name=snmp_name)
        message, status, changed = snmp_instance.delete_snmp()

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
