#!/usr/bin/python

# (C) Copyright 2020-2025 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


DOCUMENTATION = r"""
---
module: afc_leaf_spine
version_added: "0.0.1"
short_description: Create Leaf-Spine configuration.
description: >
    This module is used to configure Leaf-Spine relationship.
options:
    afc_ip:
        description: >
            IP address of the HPE ANW Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having write permission on the HPE ANW Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    data:
        description: >
            Leaf spine configuration data according to the type.
            Structure is provided in the example.
        type: dict
        suboptions:
            fabric:
                description: Fabric Name
                type: str
                required: true
            name:
                description: IP Interface Name
                type: str
                required: true
            type:
                description: Type of Leaf and Spine topology.
                type: str
                choices:
                    - l3
                    - subleaf
                required: true
            pool_ranges:
                description: >
                    L3LS specific.
                    IPv4 Resource Pool to configure ROP.
                type: str
                required: false
        required: true

author: Aruba Networks (@ArubaNetworks)
"""

EXAMPLES = r"""
-   name: Configure L3 leaf-spine settings using username and password
    arubanetworks.afc.afc_leaf_spine:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        data:
            fabric: "Aruba-Fabric"
            type: "l3"
            name: "Test-L3-LeafSpine"
            pool_ranges: "IP POOL"

-   name: Configure Subleaf leaf-spine settings using username and password
    arubanetworks.afc.afc_leaf_spine:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        data:
            fabric: "Aruba-Fabric"
            type: "subleaf"
            name: "Test-Subleaf-LeafSpine"

-   name: Configure L3 leaf-spine settings using token
    arubanetworks.afc.afc_leaf_spine:
        afc_ip: "10.10.10.10"
        auth_token: "xxlkjlsdfluwoeirkjlkjsldjjjlkj23423ljlkj"
        data:
            fabric: "Aruba-Fabric"
            type: "l3"
            name: "Test-L3-LeafSpine"
            pool_ranges: "IP POOL"

-   name: Configure Subleaf leaf-spine settings using token
    arubanetworks.afc.afc_leaf_spine:
        afc_ip: "10.10.10.10"
        auth_token: "xxlkjlsdfluwoeirkjlkjsldjjjlkj23423ljlkj"
        data:
            fabric: "Aruba-Fabric"
            type: "subleaf"
            name: "Test-Subleaf-LeafSpine"
"""

RETURN = r"""
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import (
    instantiate_afc_object,
)
from pyafc.fabric import fabric


def main():
    module_args = {
        "afc_ip": {"type": "str", "required": True},
        "afc_username": {"type": "str", "required": False},
        "afc_password": {"type": "str", "required": False},
        "auth_token": {"type": "str", "required": False},
        "operation": {"type": "str", "required": False},
        "data": {"type": "dict", "required": True},
    }

    ansible_module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True,
    )

    # Get playbook's arguments
    token = None
    ip = ansible_module.params["afc_ip"]
    if "afc_username" in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if "afc_password" in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if "auth_token" in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    data = ansible_module.params["data"]

    if token is not None:
        auth_data = {"ip": ip, "auth_token": token}
    else:
        auth_data = {"ip": ip, "username": username, "password": password}

    result = {"changed": False}

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    status = False
    changed = False
    message = ""

    afc_instance = instantiate_afc_object(data=auth_data)

    if afc_instance.afc_connected:

        fabric_instance = fabric.Fabric(
            afc_instance.client,
            name=data["fabric"],
        )

        if fabric_instance.uuid:
            if data["type"] == "l3":
                message, status, changed = fabric_instance.create_l3ls(**data)
            elif data["type"] == "subleaf":
                message, status, changed = fabric_instance.create_subleaf(
                    **data,
                )
            else:
                message = "Operation not supported - No action taken"
        else:
            message = "Fabric not found - No action taken"
            status = False
            changed = False

        # Disconnect session if username and password are passed
        if username and password:
            afc_instance.disconnect()

    else:
        message = "Not connected to AFC"

    result["message"] = message
    result["status"] = status
    result["changed"] = changed

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
