#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_vsx
version_added: "0.0.1"
short_description: Create or delete a VSX configuration in the specified fabric.
description: >
    This module creates or deletes a VSX configuration in the specified fabric.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    fabric_name:
        description: >
            Name of the Fabric where the VSX configuration will be created or deleted from.
        type: str
        required: true
    operation:
        description: >
            Operation to be performed on the VSX, create or delete.
        type: str
        required: true
    vsx_name:
        description: >
            Name of the VSX Configuration.
        type: str
        required: true
    vsx_data:
        description: >
            VSX configuration data as specified in the example below.
        type: dict
        required: true
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Create VSX
    arubanetworks.afc.afc_vsx:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        operation: "create"
        vsx_name: "Test-VSX"
        vsx_data:
            system_mac_range: "MAC POOL"
            keepalive_ip_pool_range: "IP POOL"
            keep_alive_interface_mode: "loopback"

-   name: Delete VSX
    arubanetworks.afc.afc_vsx:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        vsx_name: "Test-VSX"
        operation: "delete"
'''


RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

from pyafc.fabric import fabric
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import instantiate_afc_object


def main():
    module_args = dict(
        afc_ip=dict(type="str", required=True),
        afc_username=dict(type="str", required=False),
        afc_password=dict(type="str", required=False),
        auth_token=dict(type="str", required=False),
        fabric_name=dict(type="str", required=True),
        operation=dict(type="str", required=True),
        vsx_name=dict(type="str", required=True),
        vsx_data=dict(type="dict", required=False)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    token = None
    ip = ansible_module.params["afc_ip"]
    if 'afc_username' in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if 'afc_password' in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if 'auth_token' in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    fabric_name = ansible_module.params["fabric_name"]
    operation = ansible_module.params["operation"]
    vsx_name = ansible_module.params["vsx_name"]
    if 'vsx_data' in list(ansible_module.params.keys()):
        vsx_data = ansible_module.params["vsx_data"]

    if token is not None:
        data = {
            "ip": ip,
            "auth_token": token
        }
    else:
        data = {
            "ip": ip,
            "username": username,
            "password": password
        }

    afc_instance = instantiate_afc_object(data=data)

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    status = False
    changed = False
    message = ""

    fabric_instance = fabric.Fabric(afc_instance.client, name=fabric_name)

    if operation == 'create':
        message, status, changed = fabric_instance.create_vsx(name=vsx_name, **vsx_data)
    elif operation == 'delete':
        message, status, changed = fabric_instance.delete_vsx(name=vsx_name)

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
