#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_fabric
version_added: "0.0.1"
short_description: Assign multiple switches to the specified fabric along with role.
description: >
    This module is used to create, delete a fabric or assign multiple switches to the specified fabric along with role.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    fabric_name:
        description: >
            Name of the Fabric.
        type: str
        required: true
    operation:
        description: >
                Operation to be performed with the Fabric, create or delete or assign
        type: str
        required: true
    fabric_timezone:
        description: >
            Fabric timezone, needed for create operation
        type: str
        required: false
    devices_assignment:
        description: >
            Device assignment. The dictionary to contain IP addresses as key and roles as the value.
        type: dict
        required: true
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Assign multiple switches to the Fabric and assign role
    arubanetworks.afc.afc_fabric:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        operation: "assign"
        devices_assignment:
            10.10.10.11: "leaf"
            10.10.10.12: "leaf"

-   name: Create Fabric
    arubanetworks.afc.afc_fabric:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        fabric_timezone: "Europe/London"
        operation: "create"

-   name: Delete Fabric
    arubanetworks.afc.afc_fabric:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        operation: "delete"
'''

RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

import time
from pyafc.fabric import fabric
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import instantiate_afc_object


def main():
    module_args = dict(
        afc_ip=dict(type="str", required=True),
        afc_username=dict(type="str", required=False),
        afc_password=dict(type="str", required=False),
        auth_token=dict(type="str", required=False),
        fabric_name=dict(type="str", required=True),
        fabric_timezone=dict(type="str", required=False),
        operation=dict(type="str", required=True),
        devices_assignment=dict(type="dict", required=False)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    fabric_data = {}
    token = None
    ip = ansible_module.params["afc_ip"]
    if 'afc_username' in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if 'afc_password' in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if 'auth_token' in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    fabric_name = ansible_module.params["fabric_name"]
    operation = ansible_module.params["operation"]
    if 'devices_assignment' in list(ansible_module.params.keys()):
        devices_assignment = ansible_module.params["devices_assignment"]
    if 'fabric_timezone' in list(ansible_module.params.keys()):
        fabric_data['timezone'] = ansible_module.params["fabric_timezone"]

    if token is not None:
        data = {
            "ip": ip,
            "auth_token": token
        }
    else:
        data = {
            "ip": ip,
            "username": username,
            "password": password
        }

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    afc_instance = instantiate_afc_object(data=data)

    if operation == 'create':
        fabric_instance = fabric.Fabric(afc_instance.client, name=fabric_name, **fabric_data)
        message, status, changed = fabric_instance.create_fabric(name=fabric_name, **fabric_data)
    elif operation == 'delete':
        fabric_instance = fabric.Fabric(afc_instance.client, name=fabric_name)
        message, status, changed = fabric_instance.delete_fabric(name=fabric_name)
    elif operation == 'assign':
        fabric_instance = fabric.Fabric(afc_instance.client, name=fabric_name)
        message, status, changed = fabric_instance.add_multiple_to_fabric(devices_list=devices_assignment)
        time.sleep(60)

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
