#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_ports
version_added: "0.0.1"
short_description: Configure Ports.
description: >
    This module is used to configure ports.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    disable_tls_verification:
        description: >
            Disable TLS certificate verification when connecting to AFC.
            Only enable this for AFC instances using self-signed
            certificates.
        type: bool
        required: false
        default: false
    fabric_name:
        description: >
            Name of the Fabric.
        type: str
        required: true
    ports_data:
        description: >
            Port configuration data.
        type: dict
        required: true
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Configure Ports
    arubanetworks.afc.afc_ports:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        ports_data:
            10.10.10.7:
                "1/1/30":
                    native_vlan: 250
                "1/1/31":
                    native_vlan: 250
            10.10.10.8:
                "1/1/30":
                    native_vlan: 250
                "1/1/31":
                    native_vlan: 250
'''

RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

from pyafc.ports import ports
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import (
    afc_argument_spec,
    build_auth_data,
    instantiate_afc_object,
)


def main():
    module_args = dict(
        **afc_argument_spec(),
        ports_data=dict(type="dict", required=True)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    username = ansible_module.params["afc_username"]
    password = ansible_module.params["afc_password"]
    ports_data = ansible_module.params["ports_data"]

    data = build_auth_data(ansible_module)

    afc_instance = instantiate_afc_object(data=data)

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    message, status, changed = ports.PORT.configure_multiple_physical_port(afc_instance.client, **ports_data)

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
