#!/usr/bin/python

# (C) Copyright 2020-2025 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


DOCUMENTATION = r"""
---
module: afc_session
short_description: Create or delete session to the HPE ANW Fabric Composer
description: >
    This module creates or deletes a session to the HPE ANW Fabric Composer
version_added: "0.0.1"
options:
    afc_ip:
        description:
        - IP address of the HPE ANW Fabric Composer
        type: str
        required: true
    afc_username:
        description:
        - User account having write permission on the HPE ANW Fabric Composer
        type: str
        required: true
    afc_password:
        description:
        - Password of the user account
        type: str
        required: true
    disable_tls_verification:
        description:
        - Disable TLS certificate verification when connecting to AFC.
        - Only enable this for AFC instances using self-signed certificates.
        type: bool
        required: false
        default: false
notes:
- When re-using an auth_token, do not also provide afc_username and
  afc_password. If they are provided, the session is closed because
  authentication is considered done via username and password only.
author: Aruba Networks (@ArubaNetworks)
"""


EXAMPLES = r"""
-   name: Create a session and capture the auth_token
    arubanetworks.afc.afc_session:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        disable_tls_verification: true
    register: reg_afc_instance

-   name: Store the auth_token in a fact for re-use
    ansible.builtin.set_fact:
        auth_token: "{{ reg_afc_instance.auth_token }}"

-   name: Re-use the session with another module (token authentication)
    arubanetworks.afc.afc_fabric:
        afc_ip: "10.10.10.10"
        auth_token: "{{ auth_token }}"
        disable_tls_verification: true
        operation: create
        data:
            name: Aruba-Fabric
            timezone: Europe/London
"""


RETURN = r"""
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
headers:
    description: Headers for connection
    type: dict
    returned: always
"""

from ansible.module_utils.basic import AnsibleModule, missing_required_lib
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import (
    HAS_PYAFC,
    PYAFC_IMPORT_ERROR,
    instantiate_afc_object,
)


def main():
    module_args = {
        "afc_ip": {"type": "str", "required": True},
        "afc_username": {"type": "str", "required": True},
        "afc_password": {"type": "str", "required": True, "no_log": True},
        "disable_tls_verification": {
            "type": "bool",
            "required": False,
            "default": False,
        },
    }

    ansible_module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True,
    )

    if not HAS_PYAFC:
        ansible_module.fail_json(
            msg=missing_required_lib("pyafc"),
            exception=PYAFC_IMPORT_ERROR,
        )

    # Get playbook's arguments
    ip = ansible_module.params["afc_ip"]
    username = ansible_module.params["afc_username"]
    password = ansible_module.params["afc_password"]
    verify = not ansible_module.params["disable_tls_verification"]

    result = {"changed": False}

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    status = False
    changed = False
    message = ""
    auth_token = None

    data = {
        "ip": ip,
        "username": username,
        "password": password,
        "verify": verify,
    }

    afc_instance = instantiate_afc_object(data=data)

    if afc_instance.afc_connected:
        auth_token = afc_instance.auth_token
        message = "Successfully created afc_instance"
        status = True
        changed = True
    else:
        message = "Unable to create afc_instance"

    # Exit
    if status:
        ansible_module.exit_json(
            changed=changed,
            msg=message,
            auth_token=auth_token,
        )
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
