#!/usr/bin/python

# (C) Copyright 2020-2025 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


DOCUMENTATION = r"""
---
module: afc_remote_file_server
version_added: "0.0.1"
short_description: Create, update or delete a Remote File Transfer Server.
description: >
    This module creates, updates or deletes a Remote File Transfer Server
    (RFTS) in HPE Aruba Networking Fabric Composer. A Remote File Transfer
    Server defines an SFTP/SCP endpoint used by AFC to transfer files such
    as backup archives.
options:
    afc_ip:
        description: >
            IP address of the HPE ANW Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having write permission on the HPE ANW Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    disable_tls_verification:
        description: >
            Disable TLS certificate verification when connecting to AFC.
            Only enable this for AFC instances using self-signed
            certificates.
        type: bool
        required: false
        default: false
    operation:
        description: >
            Operation to be performed on the Remote File Transfer Server,
            create, update or delete.
        type: str
        choices:
            - create
            - update
            - delete
        required: true
    data:
        description: >
            Data of the Remote File Transfer Server as depicted in the
            example. Required for create and update operations. For delete
            only the name is required.
        type: dict
        suboptions:
            name:
                description: Name of the Remote File Transfer Server.
                type: str
                required: true
            description:
                description: Description of the RFTS configuration.
                type: str
                required: false
            remote_file_server_hostname:
                description: Hostname or IP address of the remote host.
                type: str
                required: false
            protocol:
                description: File transfer protocol to be used.
                type: str
                choices:
                    - sftp
                    - scp
                required: false
            username:
                description: Username of the Remote File Transfer Server.
                type: str
                required: false
            password:
                description: >
                    Password of the Remote File Transfer Server for the
                    above username.
                type: str
                required: false
            location:
                description: Base folder where the files need to be copied.
                type: str
                required: false
        required: true
author: Aruba Networks (@ArubaNetworks)
"""

EXAMPLES = r"""
-   name: Create a Remote File Transfer Server using username and password
    arubanetworks.afc.afc_remote_file_server:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        operation: "create"
        data:
            name: "Backup-Server"
            description: "SFTP backup target"
            remote_file_server_hostname: "10.100.100.50"
            protocol: "sftp"
            username: "backup"
            password: "backup_password"
            location: "/backups"

-   name: Update a Remote File Transfer Server
    arubanetworks.afc.afc_remote_file_server:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        operation: "update"
        data:
            name: "Backup-Server"
            remote_file_server_hostname: "10.100.100.51"

-   name: Delete a Remote File Transfer Server using token
    arubanetworks.afc.afc_remote_file_server:
        afc_ip: "10.10.10.10"
        auth_token: "xxlkjlsdfluwoeirkjlkjsldjjjlkj23423ljlkj"
        operation: "delete"
        data:
            name: "Backup-Server"
"""


RETURN = r"""
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully created remote file transfer server Backup-Server"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import (
    afc_argument_spec,
    build_auth_data,
    instantiate_afc_object,
)
from pyafc.services import rfts


def main():
    module_args = {
        **afc_argument_spec(),
        "operation": {"type": "str", "required": True},
        "data": {"type": "dict", "required": True},
    }

    ansible_module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True,
    )

    username = ansible_module.params["afc_username"]
    password = ansible_module.params["afc_password"]
    data = ansible_module.params["data"]
    operation = ansible_module.params["operation"]

    result = {"changed": False}

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    status = False
    changed = False
    message = ""

    auth_data = build_auth_data(ansible_module)

    afc_instance = instantiate_afc_object(data=auth_data)

    if afc_instance.afc_connected:

        rfts_instance = rfts.Rfts(afc_instance.client, **data)

        if operation == "create":
            message, status, changed = rfts_instance.create_rfts(**data)
        elif operation == "update":
            message, status, changed = rfts_instance.update_rfts(**data)
        elif operation == "delete":
            message, status, changed = rfts_instance.delete_rfts()
        else:
            message = "Operation not supported - No action taken"
        # Disconnect session if username and password are passed
        if username and password:
            afc_instance.disconnect()

    else:
        message = "Not connected to AFC"

    result["message"] = message
    result["status"] = status
    result["changed"] = changed

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
