#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_syslog
version_added: "0.0.1"
short_description: Create or delete a syslog client configuration.
description: >
    This module creates or deletes a syslog client configuration.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    syslog_name:
        description: >
            Name of the Syslog Client Configuration to be created or deleted.
        type: str
        required: true
    syslog_data:
        description: >
            Syslog client configuration data as per the example below.
        type: str
        required: true
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Create syslog configuration
    arubanetworks.afc.afc_syslog:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        operation: "create"
        syslog_name: "Test-Syslog"
        syslog_data:
            entry_list:
            -   host: "10.14.121.35"
                port: 514
                severity: "ERROR"
                include_auditable_events: True
                transport: "tcp"
            facility: "LOCAL7"
            fabrics:
                - 'Test-Fabric'

-   name: Delete syslog configuration
    arubanetworks.afc.afc_syslog:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        syslog_name: "Test-Syslog"
        operation: "delete"
'''


RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

from pyafc.services import syslog
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import instantiate_afc_object


def main():
    module_args = dict(
        afc_ip=dict(type="str", required=True),
        afc_username=dict(type="str", required=False),
        afc_password=dict(type="str", required=False),
        auth_token=dict(type="str", required=False),
        operation=dict(type="str", required=True),
        syslog_name=dict(type="str", required=True),
        syslog_data=dict(type="dict", required=False)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    token = None
    ip = ansible_module.params["afc_ip"]
    if 'afc_username' in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if 'afc_password' in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if 'auth_token' in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    syslog_name = ansible_module.params["syslog_name"]
    operation = ansible_module.params["operation"]
    if 'syslog_data' in list(ansible_module.params.keys()):
        syslog_data = ansible_module.params["syslog_data"]

    if token is not None:
        data = {
            "ip": ip,
            "auth_token": token
        }
    else:
        data = {
            "ip": ip,
            "username": username,
            "password": password
        }

    afc_instance = instantiate_afc_object(data=data)

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    status = False
    changed = False
    message = ""

    if operation == 'create':
        syslog_instance = syslog.Syslog(afc_instance.client, name=syslog_name, **syslog_data)
        message, status, changed = syslog_instance.create_syslog(**syslog_data)
    elif operation == 'delete':
        syslog_instance = syslog.Syslog(afc_instance.client, name=syslog_name)
        message, status, changed = syslog_instance.delete_syslog()

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
