#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_ip_interface
version_added: "0.0.1"
short_description: Crete or delete SVI.
description: >
    This module is used to create and delete Switch Virtual Interface or IP Interface.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    vrf_name:
        description: >
            Name of the VRF in which IP Interface should be created or deleted from.
        type: str
        required: true
    operation:
        description: >
            Operation to be performed with the SVI, create or delete.
        type: str
        required: true
    ip_interface_data:
        description: >
            IP Interface data containing if_type, vlan, active_gateway, ipv4_primary_address, local_proxy_arp_enabled and the switches. The values vlan and the
            prefix_length need to be integers.
        type: dict
        required: true
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Create IP Interface
    arubanetworks.afc.afc_ip_interface:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        vrf_name: "Aruba-VRF"
        operation: "create"
        ip_interface_data:
            vrf: "Aruba-VRF"
            enable: True
            local_proxy_arp_enabled: True
            name: "VLAN250"
            vlan: 250
            if_type: vlan
            ipv4_primary_address:
                address: "10.10.10.11-10.10.10.50"
                prefix_length: 24
            active_gateway:
                ipv4_address: "10.10.10.1"
                mac_address: "00:00:00:00:00:01"
            switches:
                - "10.10.10.7"
                - "10.10.10.8"
                - "10.10.10.9"

-   name: Delete IP Interface
    arubanetworks.afc.afc_ip_interface:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        vrf_name: "Aruba-VRF"
        operation: "delete"
        ip_interface_data:
            vrf: "Aruba-VRF"
            enable: True
            local_proxy_arp_enabled: True
            name: "VLAN250"
            vlan: 250
            if_type: vlan
            ipv4_primary_address:
                address: "10.10.10.11"
                prefix_length: 24
            active_gateway:
                ipv4_address: "10.10.10.1"
                mac_address: "00:00:00:00:00:01"
            switches:
                - "10.10.10.7"
'''

RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

from pyafc.fabric import fabric
from pyafc.vrf import vrf
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import instantiate_afc_object


def main():
    module_args = dict(
        afc_ip=dict(type="str", required=True),
        afc_username=dict(type="str", required=False),
        afc_password=dict(type="str", required=False),
        auth_token=dict(type="str", required=False),
        fabric_name=dict(type="str", required=True),
        vrf_name=dict(type="str", required=True),
        operation=dict(type="str", required=True),
        ip_interface_data=dict(type="dict", required=True)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    token = None
    ip = ansible_module.params["afc_ip"]
    if 'afc_username' in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if 'afc_password' in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if 'auth_token' in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    fabric_name = ansible_module.params["fabric_name"]
    vrf_name = ansible_module.params["vrf_name"]
    operation = ansible_module.params["operation"]
    ip_interface_data = ansible_module.params["ip_interface_data"]

    if token is not None:
        data = {
            "ip": ip,
            "auth_token": token
        }
    else:
        data = {
            "ip": ip,
            "username": username,
            "password": password
        }

    afc_instance = instantiate_afc_object(data=data)

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    fabric_instance = fabric.Fabric(afc_instance.client, name=fabric_name)

    vrf_instance = vrf.Vrf(afc_instance.client, name=vrf_name, fabric_uuid=fabric_instance.uuid)

    if operation == 'create':
        message, status, changed = vrf_instance.create_ip_interface(**ip_interface_data)
    elif operation == 'delete':
        message, status, changed = vrf_instance.delete_ip_interface(**ip_interface_data)

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
