#!/usr/bin/python

# (C) Copyright 2020-2025 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


DOCUMENTATION = r"""
---
module: afc_evpn_settings
version_added: "0.0.1"
short_description: Update the global EVPN settings of a fabric.
description: >
    This module updates the global (fabric-wide) EVPN settings such as ARP
    suppression, local SVI, local MAC and the VXLAN tunnel bridging mode.
options:
    afc_ip:
        description: >
            IP address of the HPE ANW Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having write permission on the HPE ANW Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    disable_tls_verification:
        description: >
            Disable TLS certificate verification when connecting to AFC.
            Only enable this for AFC instances using self-signed
            certificates.
        type: bool
        required: false
        default: false
    operation:
        description: >
            Operation to be performed on the EVPN settings.
        type: str
        choices:
            - update
        required: true
    data:
        description: >
            Global EVPN settings data.
        type: dict
        suboptions:
            fabric:
                description: Fabric Name.
                type: str
                required: true
            arp_suppression:
                description: Enable or disable ARP suppression.
                type: bool
                required: true
            local_svi:
                description: Enable or disable local SVI.
                type: bool
                required: false
            local_mac:
                description: Enable or disable local MAC.
                type: bool
                required: false
            vxlan_tunnel_bridging_mode:
                description: VXLAN tunnel bridging mode.
                type: str
                choices:
                    - ibgp-ebgp
                    - no-bridging
                required: false
            switches:
                description: >
                    List of switches on which to apply the settings. If not
                    specified, the settings apply to the whole fabric.
                type: list
                elements: str
                required: false
        required: true
author: Aruba Networks (@ArubaNetworks)
"""

EXAMPLES = r"""
-   name: Update EVPN settings using username and password
    arubanetworks.afc.afc_evpn_settings:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        operation: "update"
        data:
            fabric: "Aruba-Fabric"
            arp_suppression: true
            local_svi: true
            local_mac: true
            vxlan_tunnel_bridging_mode: "ibgp-ebgp"

-   name: Update EVPN settings using token
    arubanetworks.afc.afc_evpn_settings:
        afc_ip: "10.10.10.10"
        auth_token: "xxlkjlsdfluwoeirkjlkjsldjjjlkj23423ljlkj"
        operation: "update"
        data:
            fabric: "Aruba-Fabric"
            arp_suppression: true
"""

RETURN = r"""
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully updated EVPN Settings for fabric Aruba-Fabric"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import (
    afc_argument_spec,
    build_auth_data,
    instantiate_afc_object,
)
from pyafc.fabric import fabric


def main():
    module_args = {
        **afc_argument_spec(),
        "operation": {"type": "str", "required": True},
        "data": {"type": "dict", "required": True},
    }

    ansible_module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=True,
    )

    # Get playbook's arguments
    username = ansible_module.params["afc_username"]
    password = ansible_module.params["afc_password"]
    operation = ansible_module.params["operation"]
    data = ansible_module.params["data"]

    result = {"changed": False}

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    status = False
    changed = False
    message = ""

    auth_data = build_auth_data(ansible_module)

    afc_instance = instantiate_afc_object(data=auth_data)

    if afc_instance.afc_connected:

        fabric_instance = fabric.Fabric(
            afc_instance.client,
            name=data["fabric"],
        )

        if fabric_instance.uuid:
            settings_data = {
                key: value
                for key, value in data.items()
                if key != "fabric"
            }
            if operation == "update":
                message, status, changed = (
                    fabric_instance.update_evpn_settings(**settings_data)
                )
            else:
                message = "Operation not supported - No action taken"
        else:
            message = "Fabric not found - No action taken"

        # Disconnect session if username and password are passed
        if username and password:
            afc_instance.disconnect()

    else:
        message = "Not connected to AFC"

    result["message"] = message
    result["status"] = status
    result["changed"] = changed

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
