#!/usr/bin/python
# -*- coding: utf-8 -*-

# (C) Copyright 2019-2023 Hewlett Packard Enterprise Development LP.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = r'''
---
module: afc_vrf_bgp
version_added: "0.0.1"
short_description: Update BGP Properties or disable BGP on VRF.
description: >
    This module configures BGP properties on a VRF in the specified fabric.
options:
    afc_ip:
        description: >
            IP address of the Aruba Fabric Composer.
        type: str
        required: true
    afc_username:
        description:
        - User account having permission to create VRF on the Aruba Fabric Composer
        type: str
        required: false
    afc_password:
        description:
        - Password of the user account
        type: str
        required: false
    auth_token:
        description: >
            Auth token from the create session playbook.
        type: str
        required: false
    operation:
        description: >
            Operation to be performed with the VRF BGP, update or disable
        type: str
        required: true
    fabric_name:
        description: >
            Name of the Fabric where the VRF is located.
        type: str
        required: true
    vrf_name:
        description: >
            Name of the VRF where BGP will be configured.
        type: str
        required: true
    bgp_data:
        description: >
            BGP configuration options.
        type: dict
        required: true
author: Aruba Networks (@ArubaNetworks)
'''

EXAMPLES = r'''
-   name: Configure BGP on a VRF
    arubanetworks.afc.afc_vrf_bgp:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        vrf_name: "Aruba-VRF"
        operation: "update"
        bgp_data:
            as_number: 65000
            name: "Aruba-VRF"
            redistribute_ospf: true
            redistribute_connected: true
            redistribute_static: true
            redistribute_loopback: true
            enable: true
            trap_enable: true
            log_neighbor_changes: true
            fast_external_fallover: true
            maximum_paths: 8
            deterministic_med: true
            bestpath: true
            always_compare_med: true
            keepalive_timer: 60
            holddown_timer: 90

-   name: Disable BGP on a VRF
    arubanetworks.afc.afc_vrf_bgp:
        afc_ip: "10.10.10.10"
        afc_username: "afc_admin"
        afc_password: "afc_password"
        fabric_name: "Aruba-Fabric"
        vrf_name: "Aruba-VRF"
        operation: "disable"
        bgp_data:
            enable: false
'''

RETURN = r'''
message:
    description: The output generated by the module
    type: str
    returned: always
    sample: "Successfully completed configuration"
status:
    description: True or False depending on the action taken
    type: bool
    returned: always
    sample: True
changed:
    description: True or False if something has been changed or not
    type: bool
    returned: always
    sample: True
'''

from pyafc.fabric import fabric
from pyafc.vrf import vrf
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.arubanetworks.afc.plugins.module_utils.afc import instantiate_afc_object


def main():
    module_args = dict(
        afc_ip=dict(type="str", required=True),
        afc_username=dict(type="str", required=False),
        afc_password=dict(type="str", required=False),
        auth_token=dict(type="str", required=False),
        fabric_name=dict(type="str", required=True),
        vrf_name=dict(type="str", required=True),
        operation=dict(type="str", required=True),
        bgp_data=dict(type="dict", required=True)
    )

    ansible_module = AnsibleModule(
        argument_spec=module_args, supports_check_mode=True
    )

    # Get playbook's arguments
    token = None
    ip = ansible_module.params["afc_ip"]
    if 'afc_username' in list(ansible_module.params.keys()):
        username = ansible_module.params["afc_username"]
    if 'afc_password' in list(ansible_module.params.keys()):
        password = ansible_module.params["afc_password"]
    if 'auth_token' in list(ansible_module.params.keys()):
        token = ansible_module.params["auth_token"]
    fabric_name = ansible_module.params["fabric_name"]
    vrf_name = ansible_module.params["vrf_name"]
    operation = ansible_module.params["operation"]
    bgp_data = ansible_module.params["bgp_data"]

    if token is not None:
        data = {
            "ip": ip,
            "auth_token": token
        }
    else:
        data = {
            "ip": ip,
            "username": username,
            "password": password
        }

    afc_instance = instantiate_afc_object(data=data)

    fabric_instance = fabric.Fabric(afc_instance.client, name=fabric_name)

    vrf_instance = vrf.Vrf(afc_instance.client, name=vrf_name, fabric_uuid=fabric_instance.uuid)

    result = dict(changed=False)

    if ansible_module.check_mode:
        ansible_module.exit_json(**result)

    if operation == 'update':
        message, status, changed = vrf_instance.update_bgp_vrf(**bgp_data)
    elif operation == 'disable':
        message, status, changed = vrf_instance.update_bgp_vrf(**bgp_data)

    result['message'] = message
    result['status'] = status
    result['changed'] = changed

    # Disconnect session if username and password are passed
    if username and password:
        afc_instance.disconnect()

    # Exit
    if status:
        ansible_module.exit_json(changed=changed, msg=message)
    else:
        ansible_module.fail_json(changed=changed, msg=message)


if __name__ == "__main__":
    main()
